#!/bin/sh

file_message="${HOME}/.motd/message"
if [ -f "${file_message}" ]; then
  cat "${file_message}"
fi

if [ -x /usr/sbin/nginx ]; then
  printf "\nListe des environnements\n"
  printf "%s\n" '-------------------------------------'
  find /home/www -mindepth 1 -maxdepth 1 -type d | while read -r line ; do
    printf " - %s\n" "$(basename "${line}")"
  done
fi

if command -v docker >/dev/null 2>&1; then
  printf "\nListe des containers\n"
  printf "%s\n" '-------------------------------------'
  docker ps -a --format "{{.Names}}: {{.Status}}" | while read -r line ; do
      if echo "${line}" | grep -q " Up " >/dev/null 2>&1; then
          printf " - %b\n" "$(echo "${line}" | sed 's/^\(.\+\):\(.\+\)$/\1:\\033[0;32m\2\\033[0m/g')"
      else
          printf " - %b\n" "$(echo "${line}" | sed 's/^\(.\+\):\(.\+\)$/\1:\\033[0;31m\2\\033[0m/g')"
      fi
  done
fi
